/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_obvilion_progressbar_ProgressBar */

#ifndef _Included_ru_obvilion_progressbar_ProgressBar
#define _Included_ru_obvilion_progressbar_ProgressBar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_obvilion_progressbar_ProgressBar
 * Method:    setProgressState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_obvilion_progressbar_ProgressBar_setProgressState
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_obvilion_progressbar_ProgressBar
 * Method:    setProgressValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_obvilion_progressbar_ProgressBar_setProgressValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_obvilion_progressbar_ProgressBar
 * Method:    setWindowName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_obvilion_progressbar_ProgressBar_setWindowName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus 
}
#endif
#endif
